trigger:
- main

variables:
  tag: '$(Build.BuildId'


pool: macminipool

stages:
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      steps:
      # Build Docker image and push to ACR 
      - task: Docker@2
        inputs:
          containerRegistry: 'manual-aksdevopsacr-svc'
          repository: 'custom3aksnginxapp1'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
            $(Build.SourceVersion)
      - bash: echo contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)
      - bash: echo contents in staging artifact Directory before copying the files; ls -R $(Build.StagingArtifactDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true

      - bash: echo contents in staging artifact Directory after copying the files; ls -R $(Build.StagingArtifactDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Kube-manifests'
          publishLocation: 'Container'
          